name: MON Windows ChromeDriver Test

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # 매 시간 정각에 실행
    
permissions: 
  contents: write # 푸시 권한 부여
  
jobs:
  test:
  
    runs-on: ubuntu-latest
    # env:
    #   LANG: ko_KR.UTF-8       # 한국어 로케일 설정 (일부 환경에서만 적용됨)
    #   LC_ALL: ko_KR.UTF-8
    #   PYTHONIOENCODING: utf-8
    #   PYTHONLEGACYWINDOWSSTDIO: utf-8
      
    steps:
    - name: Set timezone
      uses: MathRobin/timezone-action@v1.1
      with:
        timezoneLinux: 'Asia/Seoul'
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # or your preferred version
        
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python main.py
    - name: Update time file 
      run: echo "$(date)" > current_time.txt 
    
    - name: Commit changes 
      run: | 
        git config --global user.name "user1" 
        git config --global user.email "user1@example.com" 
        git add current_time.txt 
        git commit -m "Update time file: $(date)" 
        git push
